apiVersion: v1
kind: ConfigMap
metadata:
  name: id-generator-config
  labels:
    app: id-generator-config
data:
  LOG_LEVEL: "debug"
  MESSAGE: "Hello, world from ConfigMap!"
  SPRING_APPLICATION_NAME: "Snowflake Id Generator"
  STARTING_EPOCH: "946684800"
  DATACENTER_ID: "1"
  WORKED_ID: "1"
