apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-config
data:
  SPRING_DATASOURCE_URL_0: "jdbc:postgresql://postgres-0.postgres:5432/app_db"
  SPRING_DATASOURCE_URL_1: "jdbc:postgresql://postgres-1.postgres:5432/app_db"
  POSTGRES_DB: "app_db"
  POSTGRES_PORT: "5432"
  POSTGRES_DRIVER_CLASS: "org.postgresql.Driver"
